name: illinois
description: Illinois client application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 5.1.0+1900

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  intl: ^0.18.0
  http: ^0.13.3
  flutter_widget_from_html: ^0.9.1
  geolocator: ^8.0.0
  url_launcher: ^6.0.10
  xml: ^6.3.0
  sprintf: ^6.0.0
  path: ^1.8.0
  collection: ^1.17.1
  convert: ^3.0.1
  roundcheckbox: ^2.0.4+1
  path_provider: ^2.0.4
  share: ^2.0.4
  qr_flutter: ^4.0.0
  webview_flutter: ^2.0.13
  app_settings: ^4.1.1
  currency_text_input_formatter: ^2.1.5
  flutter_multi_formatter: ^2.4.1
  pinch_zoom: ^1.0.0
  uuid: ^3.0.5
  expandable_page_view: ^1.0.10
  package_info: ^2.0.2
  device_calendar: ^4.0.1
  image_cropping: ^0.0.11
  dropdown_button2: ^2.1.3
  video_player: ^2.3.0
  just_audio: ^0.9.21
  flutter_barcode_scanner: ^2.0.0
  confetti: ^0.7.0
  flutter_colorpicker: ^1.0.3
  in_app_review: ^2.0.4
  speech_to_text: ^6.1.1
  visibility_detector: ^0.4.0+2
  flutter_beep: ^1.0.0
# google_maps_flutter: ^2.2.5

  rokwire_plugin:
    # When depending on this package from a real application you should use:
    #   rokwire_plugin: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: plugin

  google_maps_flutter:
    git:
      url: https://github.com/rokwire/packages.git
      path: packages/google_maps_flutter/google_maps_flutter
      ref: google_maps_flutter/add-poi-click-callback-60695

# google_maps_flutter:
#   git:
#     url: https://github.com/flutter/packages.git
#     path: packages/google_maps_flutter/google_maps_flutter
#     ref: google_maps_flutter-v2.2.5

# google_maps_flutter:
#   git:
#     url: https://github.com/riccardo-runci/google_maps_flutter.git
#     ref: main
# google_maps_flutter_platform_interface:
#     git:
#      url: https://github.com/riccardo-runci/google_maps_flutter_platform_interface.git
#      ref: main
       
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - images/
  - assets/
  - app/images/
  - app/assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ProximaNovaBlack
      fonts:
        - asset: fonts/proximanova-black.otf
    - family: ProximaNovaBlackIt
      fonts:
        - asset: fonts/proximanova-blackit.otf
    - family: ProximaNovaBold
      fonts:
        - asset: fonts/proximanova-bold.otf
    - family: ProximaNovaBoldIt
      fonts:
        - asset: fonts/proximanova-boldit.otf
    - family: ProximaNovaExtraBold
      fonts:
        - asset: fonts/proximanova-extrabold.otf
    - family: ProximaNovaExtraBoldIt
      fonts:
        - asset: fonts/proximanova-extraboldit.otf
    - family: ProximaNovaLight
      fonts:
        - asset: fonts/proximanova-light.otf
    - family: ProximaNovaLightIt
      fonts:
        - asset: fonts/proximanova-lightit.otf
    - family: ProximaNovaMedium
      fonts:
        - asset: fonts/proximanova-medium.otf
    - family: ProximaNovaMediumIt
      fonts:
        - asset: fonts/proximanova-mediumit.otf
    - family: ProximaNovaRegular
      fonts:
        - asset: fonts/proximanova-regular.otf
    - family: ProximaNovaRegularIt
      fonts:
        - asset: fonts/proximanova-regularit.otf
    - family: ProximaNovaSemiBold
      fonts:
        - asset: fonts/proximanova-semibold.otf
    - family: ProximaNovaSemiBoldIt
      fonts:
        - asset: fonts/proximanova-semiboldit.otf
    - family: ProximaNovaThin
      fonts:
        - asset: fonts/proximanova-thin.otf
    - family: ProximaNovaThinIt
      fonts:
        - asset: fonts/proximanova-thinit.otf


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
